### PR TITLE
[#1576] 2/3: QR Scan loading indicator

### LINKED ISSUE #1576: Add loading indicator for camera preview while trying to scan QR codes
**Wallet version or commit SHA:**
`design-v2` branch (9e2d017)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps:**
1. Login to your wallet
2. Click on "Send" button in the left menu
3. Click on "Enter QR Code" button
4. Click on "Capture" button

**Description:**
I'm experiencing a 5secs+ delay before preview show up, seeing a gray empty space for that time. Loading indicator would indicate that we're waiting for something.

**Screenshots/Video:**
https://i.imgur.com/88Kx0fw.gifv

### PR DESCRIPTION
**Pull request by ranbena**
Fixes #1576 

DEPENDS ON #1744. Plz do not merge before #1744 or the commit history could get messy.

**What problem does this PR solve?**
It was reported that the webcam preview might take up to 5 secs to initialize and a loading indicator is needed.

**How did you solve this problem?**
Added a loading indicator to `QRCodeScanner` which affects both Private Key Login and Send modules thanks to #1744 😋.

ezgif com-video-to-gif 1
ezgif com-video-to-gif 2

**How did you make sure your solution works?**
Manually tested that:
a) Other loading indicators remain unaffected.
b) Loading indicator shows up and runs smoothly in both cases.

**Are there any special changes in the code that we should be aware of?**
Plz notice that commits from #1744 are included so only review commit cd1b19e
I've added specific comments in the GitHub commit code.

**Is there anything else we should know?**
The cake is a lie.

- [ ] Unit tests written?

### CODE REVIEW

File: app/components/QrCodeScanner/QrCodeScanner.jsx [hunk 1]
```diff
@@ -29,15 +40,22 @@ export default class QrCodeScanner extends Component<Props> {
       callback(content, this.stopScanner.bind(this))
     })
 
-    Instascan.Camera.getCameras()
+    // since the browser halts while getting usermedia
+    // let the loading animation finish one round and only then continue
+    this.setState({ loading: true })
+    new Promise(resolve => setTimeout(resolve, 900))
```
Comment (ranbena) [inline app/components/QrCodeScanner/QrCodeScanner.jsx]: **Why force a timeout?**
Without it the loading animation hangs. Look:
ezgif com-video-to-gif 3

**Why does the animation hang?**
Because getting camera access stalls the browser. I validated this with the Chrome profiler. For about a second once `getUserMedia` is triggered the browser does absolutely nothing! I experimented with GPU layering but there doesn't seem to be a way around it.

**Why 900ms?**
That's the time it takes for the animation to complete a cycle,  and so this way, the animation hang isn't noticeable.

File: app/containers/Home/Home.scss [hunk 2]
```diff
@@ -66,6 +66,7 @@ $navigation-margin: 20px;
   display: flex;
   justify-content: center;
   min-height: 150px;
+  position: relative;
```
Comment (ranbena) [inline app/containers/Home/Home.scss]: In order for the loading indicator to position itself correctly.

File: app/components/QrCodeScanner/QrCodeScanner.jsx [hunk 3]
```diff
@@ -46,7 +64,23 @@ export default class QrCodeScanner extends Component<Props> {
...
+        {this.renderScanner()}
+      </Fragment>
+    )
+  }
+
+  renderLoadingIndicator() {
+    const { theme } = this.props
+    const { loading } = this.state
+
+    return loading ? <Loading theme={theme} nobackground /> : null
```
Comment (ranbena) [inline app/components/QrCodeScanner/QrCodeScanner.jsx]: Added a `nobackground` attribute since the default grayish background (in Loading.scss) doesn't suit the Send modal.

File: app/components/QrCodeScanner/QrCodeScanner.jsx [hunk 4]
```diff
@@ -1,12 +1,23 @@
...
-import React, { Component } from 'react'
+import React, { Component, Fragment } from 'react'
 import Instascan from 'instascan'
 
+import Loading from '../../containers/App/Loading'
+
 type Props = {
-  callback: (content: string, scannerInstance: any) => any
+  callback: (content: string, scannerInstance: any) => any,
+  theme: string
```
Comment (ranbena) [inline app/components/QrCodeScanner/QrCodeScanner.jsx]: Whoops.. forgot to add `withThemeData` to `index.jsx`. Would force push but the GitHub comments I put in the code would get trampled :( I'll wait till you approve?

File: app/components/QrCodeScanner/QrCodeScanner.jsx (hunk 1 above)
Comment (dvd-schwrtz) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: Ha, I just asked about this on another PR. Perhaps add a variable name to explain or a comment

File: app/components/QrCodeScanner/QrCodeScanner.jsx [hunk 5]
```diff
@@ -29,15 +40,22 @@ export default class QrCodeScanner extends Component<Props> {
       callback(content, this.stopScanner.bind(this))
     })
 
-    Instascan.Camera.getCameras()
+    // since the browser halts while getting usermedia
+    // let the loading animation finish one round and only then continue
+    this.setState({ loading: true })
+    new Promise(resolve => setTimeout(resolve, 900))
+      .then(() => Instascan.Camera.getCameras())
       .then((cameras: Array<Object>) => {
```
Comment (dvd-schwrtz) [inline app/components/QrCodeScanner/QrCodeScanner.jsx]: Do we want to run validation through something like joi on the returned objects perhaps to make sure the cameras in the array are in the right format? Maybe this is already happening in the getCameras() call. If not, might be a good idea

Comment (dvd-schwrtz) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: Also, as far as using instascan and other libraries, in general the less libraries we use, the better. we will be implementing more security around npm package management moving forward. However, if it is helpful, of course we can use packages

Comment (ranbena) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: > Also, as far as using instascan and other libraries, in general the less libraries we use, the better. we will be implementing more security around npm package management moving forward. However, if it is helpful, of course we can use packages

Indeed I try to use as less packages as possible. This one ain't new though, it's been used up till now. It's not great in terms of maintenance, error handling nor static typing. I think though this type of consideration would be out of scope for this issue, don't you think?

Comment (dvd-schwrtz) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: Yes, was just bringing it up :)

Comment (ranbena) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: > Do we want to run validation through something like joi on the returned objects perhaps to make sure the cameras in the array are in the right format? Maybe this is already happening in the getCameras() call. If not, might be a good idea

Not sure it's a must in this case since it's an `Instascan` method feeding into another. I changed the original code to Promise chaining in order for the `catch` to attain to any errors in this process.

**Comment by ranbena** [comment]
@dvd-schwrtz requested changes pushed

File: app/components/QrCodeScanner/QrCodeScanner.jsx (hunk 1 above)
Comment (comountainclimber) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: @ranbena this is awesome just curious is there a fixed amount of time it takes for camera to render? Is that dependent on hardware?

File: app/components/QrCodeScanner/QrCodeScanner.jsx (hunk 4 above)
Comment (comountainclimber) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: Thats fine 👍

File: app/components/QrCodeScanner/QrCodeScanner.jsx (hunk 1 above)
Comment (ranbena) [reply app/components/QrCodeScanner/QrCodeScanner.jsx]: That's a good question. I found no info on the web. Any suggestion/reference would be welcome.

If the render time takes longer on other systems, it would result in a longer time between the completed animation cycle and the actual preview coming up. I think it's the best we got at this time.
