### PR TITLE
[#1640] Added wallet import name duplication validation

### LINKED ISSUE #1640: There is no validation on wallet name while importing new wallets from *.json file
**Wallet version or commit SHA:**
`design-v2` branch (b2519ef)

**Environment:**
MacBook Pro (13-inch, 2017), macOS Mojave 10.14

**Reproduction steps:**
1. Create a new wallet named "test"
2. Login to newly created wallet
3. Click on "Settings" button in the left menu
4. Click on "Export" button and save *.json file anywhere
5. Close your Neon wallet and clear it's app data (fresh Neon wallet installation)
6. Start Neon wallet
7. Create a new wallet named "test"
8. Login to newly created wallet
9. Click on "Settings" button in the left menu
10. Click on "Import" button and choose previously saved *.json file
11. Logout from current wallet
12. Click on drop-down with saved wallet => you can see 2x "test", both of them will login you to the wallet which was created as 1st

**Description:**
If you have a saved wallet named "test" and then you import a *.json file with another wallet which has exactly the same name ("test") - you will end up having 2x "test" wallet in the app. You're able to login only to first wallet created (saved wallet in this case), doesn't matter which "test" wallet you're going to choose from drop-down list (1st "test" or 2nd "test") - it will always log you in to the 1st one.

**Screenshots/Video:**
Video is taken from 6th reproduction step (after saving *.json file with a wallet named "test"):
https://i.imgur.com/h3LEgkq.gifv

### PR DESCRIPTION
**Pull request by ranbena**
Fixes #1640 

Showing error message if account label in imported wallet already exists in a current account.
Intersecting account labels in current wallet and imported wallet as an indication of dupe name.

import

### CODE REVIEW

File: app/modules/generateWallet.js [hunk 1]
```diff
@@ -151,6 +151,13 @@ export const recoverWallet = (wallet: Object): Promise<*> =>
         reject(Error('No accounts found in recovery file.'))
       }
 
+      // check if wallet label already exists
+      const duplicateLabels = intersectionBy(data.accounts, accounts, 'label')
+
+      if (duplicateLabels.length) {
```
Comment (evgenyboxer) [inline app/modules/generateWallet.js]: @ranbena I think we should be explicit about number comparison... how about `duplicateLabels.length === 0`?

Comment (ranbena) [reply app/modules/generateWallet.js]: Np, but why tho? It's readable and fail-safe.

Comment (ranbena) [reply app/modules/generateWallet.js]: It's a fetish of mine.. writing code as minimal as possible.

Especially this one 🐒
```
if (~arr.indexOf('foo')) {
  ...
}
```

Comment (evgenyboxer) [reply app/modules/generateWallet.js]: or this one: `if (!0) { ... }` 😄

Comment (ranbena) [reply app/modules/generateWallet.js]: Anywho, I updated the PR.
