### PR TITLE
[#1619] New wallet form validation

### LINKED ISSUE #1619: design-v2(UX): [Enhance] Create Wallet: No status message or user message feedback for passwords that do not match
**Wallet version or commit SHA:**
2.0.0

**Environment:**
Ubuntu Linux 16.04

**Prerequisites:**
None

**Reproduction steps:**
1. Click "Manage Wallets"
2. Click "Create"
3. Fill out information
4. Enter passwords that do not match

When passwords do not match there is no status message. One has to click both eyes to understand why the create wallet button is grey.

### PR DESCRIPTION
**Pull request by ranbena**
Fixes #1619 

Utilized the input error message mechanism. Nothing fancy. Pretty straight forward.
No new tests added.

### How it works
Password validator - at least 4 chars
Confirm validator - matches password
(Empty fields show no error message since it's redundant and bad for UX)

Feel free to suggest alternative error message texts.

pass

### CODE REVIEW

File: app/containers/CreateWallet/CreateWallet.jsx [hunk 1]
```diff
@@ -114,15 +124,15 @@ export default class CreateWallet extends React.Component<Props, State> {
               />
               <PasswordInput
                 label="Passphrase"
-                value={passphrase}
-                onChange={e => this.setState({ passphrase: e.target.value })}
+                onChange={this.handleChangePassphrase}
                 placeholder="Password"
+                error={this.state.passphraseError}
```
Comment (evgenyboxer) [inline app/containers/CreateWallet/CreateWallet.jsx]: super minor, since we are destructing state on line `71`, could move `passphraseError` there too for consistency?

File: app/containers/CreateWallet/CreateWallet.jsx [hunk 2]
```diff
@@ -114,15 +124,15 @@ export default class CreateWallet extends React.Component<Props, State> {
...
               />
               <PasswordInput
                 label="Confirm Passphrase"
-                value={passphrase2}
-                onChange={e => this.setState({ passphrase2: e.target.value })}
+                onChange={this.handleChangePassphrase2}
                 placeholder="Confirm Password"
+                error={this.state.passphrase2Error}
```
Comment (evgenyboxer) [inline app/containers/CreateWallet/CreateWallet.jsx]: same as the above comment ^

File: app/containers/CreateWallet/CreateWallet.jsx [hunk 3]
```diff
@@ -26,15 +26,25 @@ type Props = {
...
+  passphraseValid: boolean,
+  passphrase2Valid: boolean,
+  passphraseError: string,
+  passphrase2Error: string,
   wif: string,
   walletName: string,
   submitButtonDisabled: boolean
 }
 
+const PASS_MIN_LENGTH = 4
```
Comment (comountainclimber) [inline app/containers/CreateWallet/CreateWallet.jsx]: 👍

**Comment by ranbena** [comment]
Added requested changes and ready for shipping!
love-boat
