### PR TITLE
Fixed panel flickering on retry button (fixes #1080)

### LINKED ISSUE #1080: Content under "Failed to load. Retry?" flickers while "Retry?" button is clicked
**Wallet version or commit SHA:**
0f2951a

**Environment:**
Win 10 Home (64 bit) Version 1709 Build 16299.431

**Prerequisites:**
At least one wallet imported to the app
Disconnect internet connection

**Reproduction steps:**
1. Start Neon Wallet
2. Click on "Login using a saved wallet" button
3. Select your wallet, enter your passphrase and click on "Login" button
4. Click on "Retry?" button several times in a row

Sometimes it happens on a first click, sometimes not. Easiest way to reproduce this issue is to click "Retry?" several times in a row.

**Screenshots/Video:**
flickering_under

### PR DESCRIPTION
**Pull request by alexhulbert**
**What current issue(s) from Trello/Github does this address?**
Issue #1080 

**What problem does this PR solve?**
Currently, when you click the "retry" button, spunky automatically loads up the previous state of the panel and shows it until axios fails to grab necessary information. This causes the previous working state of a panel to sometimes pop up for a fraction of a second when you click the "retry" button.

**How did you solve this problem?**
By switching to the "recentlyCompleted" in the load cycle, spunky now assumes the following: If a panel is currently in the "FAILED" state, it will most likely fail again. This prevents the previous state from flashing onto the screen while still keeping the normal refresh button behavior the same. 

**How did you make sure your solution works?**
I tried the following cases:
- Wallet starts with an internet connection, refresh button is pressed
- Wallet starts with an internet connection, the internet is disconnected, refresh button is pressed.
- Wallet starts without an internet connection, retry button is pressed
- Wallet starts without an internet connection, the internet is connected, retry button is pressed
- Combinations of the 2nd and 4th bullet points without closing the wallet.

**Is there anything else we should know?**
I discovered another bug while testing this one. This bug can cause the wallet to crash when connecting or disconnecting the internet while the wallet is open. The other bug will be fixed in my next PR. For the best results, merge my next pull request before testing this one (or at least cherry-pick the commits into your local workspace).

### CODE REVIEW

File: app/hocs/withProgressPanel.js [hunk 1]
```diff
@@ -10,7 +10,8 @@ const mapActionsToProps = (action, props) => ({
   onRetry: () => action.call(props)
 })
 
-export default function withProgressPanel (actions, { title, strategy = alreadyLoadedStrategy, ...options } = {}) {
+export default function withProgressPanel (actions, { title, strategy = recentlyCompletedStrategy, ...options } = {}) {
+  console.log(actions, options, title)
```
Comment (evgenyboxer) [inline app/hocs/withProgressPanel.js]: Sneaky `console.log`

Comment (alexhulbert) [reply app/hocs/withProgressPanel.js]: Oops. Thought I removed that with a git commit --amend. Somehow they always make it into the PRs :shipit:
